---
abstract: 'core flux interfaces'
author:
  - 'Vyacheslav Matyukhin <me@berekuk.ru>'
build_requires:
  Params::Validate: 0
  Test::Class: 0
  Test::Fatal: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Flux
requires:
  Carp: 0
  Exporter: 0
  List::Util: 0
  Moo: 0
  Moo::Role: 0
  Scalar::Util: 0
  overload: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/berekuk/Flux.git
version: 1.01
